### ISSUE TITLE
0.8.0 build fails on i686

### ISSUE THREAD

**Issue by lgbaldoni** [ultravideo/uvg266#12]
And presumably on all non x86_64 architectures.

See [build log](https://github.com/ultravideo/uvg266/files/12736541/uvg266_i586.txt).

(OS: openSUSE Tumbleweed)

**Comment by Jovasa** [comment]
If you comment this line does it compile then https://github.com/ultravideo/uvg266/blob/9add13b7053a6ba3f6b22bf82728e01fc437a447/src/strategies/avx2/dct-avx2.c#L55

**Comment by lgbaldoni** [comment]
> If you comment this line does it compile then
> 
> https://github.com/ultravideo/uvg266/blob/9add13b7053a6ba3f6b22bf82728e01fc437a447/src/strategies/avx2/dct-avx2.c#L55

It does.

**Comment by Jovasa** [comment]
Fixed with e5e32d67f43ba73db4a1a17aa975a070f15496be
