### ISSUE TITLE
Is it possible to add support for AVX-512 in a future release?

### ISSUE THREAD

**Issue by jiangzemin-xudamin** [ultravideo/uvg266#29]
SVT-AV1 both support AVX-512, when will UVG266 follow suit?

**Comment by fador** [comment]
Hi,
Yes it's definitely possible in the future, I think they are more useful for 10+bit encoding, not so much for the 8bit.
The only problem is that there's exactly one person in our team working on the optimizations so it will take a while 😅
Also we are still working on making uvg266 overall better and more stable, e.g. I don't think the 10bit encoding is working as it should at the moment..

**Comment by jiangzemin-xudamin** [comment]
thanks

**Comment by maa7** [comment]
As far as i know uvg266 is written in high level C language, and support for certain sets of SIMD instructions must be specified by compiler switches by specifying the target platform.
So what do you mean by "add support for AVX-512 in a future release"?

**Comment by fador** [comment]
> So what do you mean by "add support for AVX-512 in a future release"?

Sure the compiler option for generating AVX-512 can be enabled but it will not optimize our code too much, we have to manually implement the optimizations to actually take use of the new register width. It can also mean changing the algorithms to fit AVX-512 better.
We use C Intrinsic functions to write the optimizations, as an example all the AVX2 stuff is here: https://github.com/ultravideo/uvg266/tree/master/src/strategies/avx2

**Comment by maa7** [comment]
> we have to manually implement the optimizations to actually take use of the new register width. We use C Intrinsic functions to write the optimizations, as an example all the AVX2 stuff is here
"generic" folder size =413 KB
"avx2" folder size =1104 KB
but this approach requires a huge investment of effort and time! in fact, you wrote a second program in AVX2 assembler, and will be forced to manually write a new program for each new set of SIMD instructions.

> compiler option for generating AVX-512 can be enabled but it will not optimize our code too much
have you tried C with ISPC?
